In [1]:
from pandas_profiling import ProfileReport
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("advertising.csv")
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [3]:
pf=ProfileReport(df)
pf.to_widgets()

In [4]:
pf.to_file('ad.html')

In [5]:
x=df[['TV']] #by default it only takes 2d [[[inputs]]] 2d array or vector
x

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [6]:
y=df['Sales']
y

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

In [7]:
# sales=m*TV + c
#sklearn (each and every mathematical operation to function)


In [8]:
from sklearn.linear_model import LinearRegression
li = LinearRegression()
li.fit(x,y)

LinearRegression()

In [9]:
li.intercept_ #c

6.9748214882298925

In [10]:
li.coef_ #m

array([0.05546477])

In [11]:
file='linear_reg.sav'         #saving to physical file 
pickle.dump(li, open(file, 'wb'))

In [12]:
saved_model=pickle.load(open(file, 'rb'))

In [13]:
saved_model.predict([[45]])

array([9.47073616])

In [44]:
li.score(x,y) #give seperate data

0.8121757029987414

In [45]:
1085%9

5

In [46]:
data_x = df.iloc[:,:3]
data_x=df[['TV', 'Radio', 'Newspaper']]

In [47]:
data_x

TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [48]:
y=df.Sales
y

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

In [49]:
lm = LinearRegression()
lm.fit(data_x, y)

LinearRegression()

In [50]:
lm.intercept_

4.625124078808655

In [51]:
lm.coef_

array([0.05444578, 0.10700123, 0.00033566])

In [52]:
lm.score(data_x, y)

0.9025912899684558

In [58]:
import statsmodels.formula.api as smf
lm=smf.ols(formula='Sales ~ TV+Radio', data=df).fit() #give you statistics
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.902
Method:                 Least Squares   F-statistic:                     912.7
Date:                Fri, 13 Jan 2023   Prob (F-statistic):          2.39e-100
Time:                        16:38:36   Log-Likelihood:                -383.34
No. Observations:                 200   AIC:                             772.7
Df Residuals:                     197   BIC:                             782.6
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.6309      0.290     15.952      0.000       4.058       5.203
TV             0.0544      0.001     39.726      0.000       0.052       0.057
Radio          0.1072      0.008     13.522      0.000       0.092       0.123
==============================================================================
Omnibus:                       16.227   Durbin-Watson:                   2.252
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.973
Skew:                          -0.434   Prob(JB):                     8.43e-07
Kurtosis:                       4.613   Cond. No.                         425.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""